#settings
GiveItemsOnJoin: true
GiveItemsOnRespawn: true
ClearItemsAfterUse: true
workingworlds:
- Lobby
#please dont add more slots
slot1: 276
slot1-Tip: §6Tap on the ground to go to PvP!
slot1-command: mw tp {PLAYER} world

slot2: 267
slot2-Tip: §6Tap on the ground to go to 1vs1!
slot2-command: tp {PLAYER} -881 6 233

slot3: 261
slot3-Tip: §6Tap on the ground to go to Skywars!
slot3-command: tp {PLAYER} -909 7 304

slot4: 1
slot4-Tip: §6Tap on the ground to go to MyPlot!
slot4-command: mw tp {PLAYER} plot

slot5: 283
slot5-Tip: §6Tap on the ground to go to SurvivalGames!
slot5-command: tp {PLAYER} -811 7 203

slot6: 339
slot6-Tip: §6Tap on the ground to see your money!
slot6-command: rca {PLAYER} mymoney
