#settings
GiveItemsOnJoin: true
GiveItemsOnRespawn: true
ClearItemsAfterUse: true
workingworlds:
- Lobby

# Setup a slots in following format
slots:
 276:
  tip: "§6Tap on the ground to go to PvP!"
  commands:
   - "mw tp {PLAYER} world"
  355:
  tip: "§6Tap on the ground to go to Hotel!"
  commands:
   - "mw tp {PLAYER} Gamecraft Hotel original"
  261:
  tip: "§6Tap on the ground to go to Skywars!"
  commands:
   - "tp {PLAYER} 1055 5 -473"
  1:
  tip: "§6Tap on the ground to go to MyPlot!"
  commands:
   - "mw tp {PLAYER} plot"
  339:
  tip: "§6Tap on the ground to go to see your money!"
  commands:
   - "rca {PLAYER} mymoney" 
