#settings
GiveItemsOnJoin: true
GiveItemsOnRespawn: true
ClearItemsAfterUse: true
workingworlds:
- Lobby
#please dont add more slots
slot1: 267
slot1-Tip: §6Tap on the ground to go to PvP Games!
slot1-command: rca {PLAYER} transfer 3

slot2: 256
slot2-Tip: §6Tap on the ground to go to Spleef!
slot2-command: rca {PLAYER} transfer 5

slot3: 261
slot3-Tip: §6Tap on the ground to go to Skywars!
slot3-command: rca {PLAYER} transfer 3

slot4: 1
slot4-Tip: §6Tap on the ground to go to MyPlot!
slot4-command: rca {PLAYER} transfer 2

slot5: 296
slot5-Tip: §6Tap on the ground to go to SurvivalGames!
slot5-command: rca {PLAYER} transfer 4

slot6: 339
slot6-Tip: §6Tap on the ground to see your money!
slot6-command: rca {PLAYER} mymoney
